import { AppImages } from "../../../assets/images/AppImages";

export const contentData = [
    {
        id:1,
        image:AppImages.abudhabi1,
        title:"abudhabi",
        desc:"UAE"
    },
    {
        id:2,
        image:AppImages.bigben,
        title:"bigben",
        desc:"London"
    },
    {
        id:3,
        image:AppImages.istanbul,
        title:"Istanbul",
        desc:"Türkiye"
    },
    {
        id:4,
        image:AppImages.cologne,
        title:"Cologne",
        desc:"Germany"
    },
    {
        id:5,
        image:AppImages.lasvegas2,
        title:"Las Vegas",
        desc:"USA"
    },
    {
        id:6,
        image:AppImages.california,
        title:"California",
        desc:"USA"
    },
    {
        id:7,
        image:AppImages.sydney,
        title:"Sydney",
        desc:"Australia"
    },
    {
        id:8,
        image:AppImages.toronto,
        title:"Toronto",
        desc:"Canada"
    },
    {
        id:9,
        image:AppImages.lahore,
        title:"Lahore",
        desc:"Pakistan"
    },
    {
        id:10,
        image:AppImages.islamabad,
        title:"Islamabad",
        desc:"Pakistan"
    },
    {
        id:11,
        image:AppImages.mumbai,
        title:"Mumbai",
        desc:"Pakistan"
    },
    {
        id:12,
        image:AppImages.hongkong,
        title:"HongKong",
        desc:"SpecialChina"
    },
]