export const countrydetail = [
  {
    id: 1,
    country: 'United Arab Emirates',
    city: 'Dubai',
    canceltxt: 'Free cancellation',
    price: '$23',
    rating: '4.6',
    desc: 'Uncover the secrets of Dubai, a city of superlatives where every experience is grander than the last. From skydiving over the iconic Palm Jumeirah to skiing in the middle of the desert at Ski Dubai, this city is a playground for thrill-seekers and luxury lovers alike. Stroll along the glamorous Dubai Marina, sip cocktails at rooftop bars overlooking the city skyline, or explore the traditional neighborhoods of Bastakiya and Al Fahidi. Dubai is a destination that combines the best of both worlds, offering a blend of modernity and tradition unlike anywhere else.',
    image: require('../../../assets/images/country1.png'),
    
  },
  {
    id: 2,
    country: 'Istanbul',
    city: 'Türkiye',
    canceltxt: 'Free cancellation',
    price: '$18',
    rating: '4.6',
    desc:'Delve into the magic of Istanbul, a city that captures the imagination with its unique blend of ancient wonders and modern delights. Indulge in the sensory delights of Turkish coffee, delight in the intricate beauty of the Blue Mosque, and lose yourself in the maze of streets that make up this dynamic and vibrant city.',
    image: require('../../../assets/images/country2.png'),
  },
  {
    id: 3,
    country: 'London',
    city: 'Big Ben',
    canceltxt: 'Free cancellation',
    price: '$38',
    rating: '4.6',
    desc:'Discover the magic of Big Ben, one of London\'s most famous landmarks. Whether you\'re admiring its elegant silhouette from afar or climbing to the top for a closer look, this historic clock tower is sure to leave a lasting impression on all who visit.Visit Big Ben and experience the beauty of its intricate design and rich history. With its distinctive Gothic architecture and melodious chimes, this world-famous clock tower is a must-visit destination for tourists and history enthusiasts alike.',
    image: require('../../../assets/images/country3.png'),
  },
  {
    id: 4,
    country: 'Germany',
    city: 'Cologne',
    canceltxt: 'Free cancellation',
    price: '$32',
    rating: '4.6',
    desc:'Unleash your confidence and allure with our exquisite Cologne, a must-have accessory for every man who appreciates the finer things in life. Indulge in the harmonious mix of fresh, invigorating scents that captivate the senses and elevate your presence from day to night.Enhance your daily grooming routine with our premium Cologne, crafted with a sophisticated blend of aromatic notes that exude elegance and charm. Immerse yourself in the luxurious scent that lasts all day, leaving a lasting impression wherever you go.',
    image: require('../../../assets/images/country4.png'),
  },
  {
    id: 5,
    country: 'Thailand',
    city: 'Bangkok',
    canceltxt: 'Free cancellation',
    price: '$30',
    rating: '4.6',
    desc:'Bangkok, the vibrant capital city of Thailand, is a bustling metropolis renowned for its dynamic blend of modernity and tradition. As a vital economic and cultural hub in Southeast Asia, Bangkok boasts a rich tapestry of historical landmarks, iconic temples, and bustling markets. With its diverse culinary scene, from street food stalls to Michelin-starred restaurants, Bangkok offers a tantalizing gastronomic experience for visitors. The city\'s intricate network of waterways, skyscrapers, and vibrant nightlife showcases its multifaceted identity, attracting millions of tourists annually. Its ornate temples like Wat Arun and the Grand Palace stand as testaments to its deep-rooted heritage and spiritual legacy.Furthermore, Bangkok\'s status as a global business hub is exemplified through its modern infrastructure, world-class conference venues, and innovative start-up ecosystem. In essence, Bangkok embodies a unique juxtaposition of old-world charm and contemporary sophistication, making it a captivating destination for travelers and professionals alike.',
    image: require('../../../assets/images/country5.png'),
  },
  {
    id: 6,
    country: 'Canada',
    city: 'Lake Lois,Alberta',
    canceltxt: 'Free cancellation',
    price: '$119',
    rating: '4.6',
    desc:'Lake Louise in Alberta is a breathtaking natural wonder nestled within Banff National Park. Renowned for its turquoise, glacier-fed waters, surrounded by towering mountain peaks, and an iconic chateau on its shoreline, Lake Louise attracts millions of visitors each year. This pristine alpine lake offers a multitude of recreational activities, including hiking, canoeing, and photography opportunities. The calming beauty of Lake Louise makes it an ideal destination for nature enthusiasts and photographers looking to capture the essence of the Canadian Rockies. With its stunning vistas and serene ambiance, Lake Louise truly epitomizes the majestic wilderness of Alberta, inviting visitors to immerse themselves in the unparalleled natural beauty found in this iconic destination.',
    image: require('../../../assets/images/country6.png'),
  },
  {
    id: 7,
    country: 'Switzerland',
    city: 'Grindelwald',
    canceltxt: 'Free cancellation',
    price: '$23',
    rating: '4.3',
    desc:'Grindelwald, a village nestled in the Swiss Alps, boasts a rich history and breathtaking scenery that attracts visitors from around the world. Known for its charming chalet-style architecture and stunning mountain views, Grindelwald offers a perfect blend of relaxation and outdoor adventure. Professional travelers seeking a tranquil retreat often find solace in the serene atmosphere of Grindelwald, where opportunities for skiing, hiking, and exploring the surrounding glaciers abound. With a selection of luxury hotels, fine dining establishments, and boutique shops, Grindelwald caters to the discerning traveler looking to unwind in style amidst the splendor of nature. Whether admiring the Eiger North Face or immersing oneself in the local culture at traditional Swiss festivals, Grindelwald promises a sophisticated yet soul-nourishing travel experience for those in search of refined leisure pursuits.',
    image: require('../../../assets/images/country7.png'),
  },
  {
    id: 8,
    country: 'Maldives',
    city: 'Jewel Of Indian Ocean',
    canceltxt: 'Free cancellation',
    price: '$23',
    rating: '4.2',
    desc:'The Maldives, often referred to as the "Jewel of the Indian Ocean," is a tropical paradise renowned for its pristine white sandy beaches, crystal-clear turquoise waters, and vibrant coral reefs. This archipelago of 26 atolls is a haven for luxury travelers seeking an exclusive and indulgent escape. The overwater bungalows perched above the azure lagoons offer unparalleled views and a sense of serenity like no other. The Maldives is not only a popular destination for romantic getaways and honeymooners but also an ideal spot for snorkeling, scuba diving, and exploring marine life. With its world-class resorts, impeccable service, and breathtaking natural beauty, the Maldives truly lives up to its reputation as a luxury paradise in the heart of the Indian Ocean.',
    image: require('../../../assets/images/country8.png'),
  },
  {
    id: 9,
    country: 'Czech Republic',
    city: 'Prague',
    canceltxt: 'Free cancellation',
    price: '$61',
    rating: '4.6',
    desc:'Prague, the capital city of the Czech Republic, is a bustling metropolis steeped in rich history and culture. Known for its stunning architecture, including the iconic Prague Castle and the historic Charles Bridge, this city attracts millions of tourists from around the world each year. With a vibrant arts scene, renowned museums, and a thriving culinary community, Prague offers a diverse range of experiences for visitors to enjoy. Its cobblestone streets and charming old town create a picturesque backdrop that is sure to captivate any traveler. Furthermore, Prague\'s strategic location in the heart of Europe makes it a hub for business and commerce, hosting numerous international conferences and events throughout the year. Overall, Prague stands as a testament to the enduring allure of a city that seamlessly blends the past with the present, making it a must-visit destination for those seeking a truly unforgettable experience.',
    image: require('../../../assets/images/country9.png'),
  },
  {
    id: 10,
    country: 'Switzerland',
    city: 'Lucerne',
    canceltxt: 'Free cancellation',
    price: '$46',
    rating: '4.6',
    desc:'Nestled in the heart of Switzerland, Lucerne stands as a picturesque city known for its striking blend of natural beauty and rich cultural heritage. Boasting a backdrop of the stunning Swiss Alps and tranquil Lake Lucerne, the city exudes a sense of tranquility and charm that captivates visitors from around the world. Lucerne\'s well-preserved medieval architecture, including the iconic Chapel Bridge and historic Old Town, provides a glimpse into its storied past and offers a delightful meander through cobblestone streets lined with boutique shops and inviting cafes. As a hub of artistic and musical expression, Lucerne hosts the renowned Lucerne Festival, attracting top performers and cultural enthusiasts alike. With its impeccable cleanliness, efficient public transportation, and warm hospitality, Lucerne epitomizes Swiss precision and elegance, making it a must-visit destination for both leisure travelers and professional events alike.',
    image: require('../../../assets/images/country10.png'),
  },
  {
    id: 11,
    country: 'Singapore',
    city: 'Merlion',
    canceltxt: 'Free cancellation',
    price: '$23',
    rating: '4.6',
    desc:'The Merlion in Singapore stands as an iconic symbol of the country\'s heritage and culture, blending the qualities of a lion and a fish to represent the city\'s origins as a fishing village and its transformation into a modern metropolis. Standing at an impressive 28 feet tall and weighing an impressive 70 tons, the Merlion monument in Merlion Park has become a must-visit destination for tourists worldwide, symbolizing Singapore\'s prosperity and strength. The majestic statue also overlooks the stunning Marina Bay, providing breathtaking views and serving as a testament to the city-state\'s booming tourism industry. As a landmark embodying the fusion of Singapore\'s past and future, the Merlion continues to attract visitors seeking to capture the essence of this vibrant island nation in one captivating image.',
    image: require('../../../assets/images/country11.png'),
  },
  {
    id: 12,
    country: 'Luxemborg',
    city: 'Echternach Town',
    canceltxt: 'Free cancellation',
    price: '$230',
    rating: '4.2',
    desc:'Echternach Town, located in Luxembourg, is a captivating destination known for its rich history and picturesque charm. Steeped in tradition, this quaint town draws visitors with its well-preserved medieval architecture, including the iconic basilica and the imposing remains of the Abbey of Echternach. As a center of culture and heritage, Echternach offers a blend of modern amenities alongside its historic sites, making it a unique place to explore. The town is also renowned for its annual Dancing Procession, a centuries-old folklore event that attracts people from far and wide, adding a touch of mystique and cultural significance to the town. With its scenic surroundings, charming cobblestone streets, and welcoming atmosphere, Echternach Town is a must-visit destination for those seeking a blend of history, culture, and natural beauty in a single location.',
    image: require('../../../assets/images/country12.png'),
  },
];
