export const AppImages={
    loginback :  require('../images/Loginbackground.png'),
    loginbackimage :  require('../images/LoginBackground2.png'),
    signupbackground :  require('../images/background3.jpg'),
    google : require('../images/Google.png'),
    apple : require('../images/Apple.png'),
    applogo : require('../images/AppLogo.png'),
    onboarding : require('../images/onboarding1.jpg'),
    onboarding2 : require('../images/onboarding2.jpg'),
    onboarding3 : require('../images/onboarding3.jpg'),
    onboarding4 : require('../images/onboarding4.jpg'),
    arrowright : require('../images/ArrowRightOutline.png'),
    openeye : require('../images/showpass.png'),
    closeeye : require('../images/Password-Outline.png'),
    cardoutline : require('../images/CardOutline.png'),
    email : require('../images/Email-Bulk.png'),
    phone : require('../images/Phone-Fill.png'),
    leftnav : require('../images/Chevron-Left.png'),
    passchange : require('../images/passchange.png'),
    error : require('../images/error.png'),
    success : require('../images/success.png'),
    info : require('../images/info.png'),
    warning : require('../images/warning.png'),
    check : require('../images/check.png'),
    cross : require('../images/cross.png'),
    
    
}